Allow AWS_REGION on input variables
cloudposse/terraform-aws-codebuild pull request #101
Opened 2022-01-12 10:07 UTC by batistadasilva

## what
* Allow passing `AWS_REGION` on input `environment_variables`

## why
* My organization needs to to run our application on a Codebuild task using the same environment variables as the production instance, so it is more practical to copy those values automatically. However, the production instance already contains a `AWS_REGION`, which currently causes conflicts with the variables created by this module.

Thank you

2022-01-12 10:09 UTC, batistadasilva commented on main.tf
> +    dynamic "environment_variable" {
it doesn't seem that this lack of security was introduced by this Pull Request

2022-03-15 13:39 UTC, batistadasilva commented
Any news on this patch?

2022-03-15 15:50 UTC, Gowiem commented on main.tf
> +      for_each = signum(length(var.aws_account_id)) == 0 && contains(var.environment_variables.*.name, "AWS_REGION") ? [] : [1]
@batistadasilva Why the `aws_account_id` check?

2022-03-15 15:53 UTC, Gowiem requested changes
In general, this seems like a problem of your usage of the module rather than a problem others would have, which makes me hesitant for us to accept it. 

I'm wondering if you can approach it from a different angle... Can you not filter out the `AWS_REGION` key/val from your `var.environment_variables` input when you're consuming this module? That seems like the ideal solution. 

If you can share some other reasons why the larger community would need this patch then I'm happy to discuss, but my gut feeling is that this doesn't make sense unfortunately.

2022-06-06 15:58 UTC, batistadasilva commented
@Gowiem Thank you for the explanation

I am gonna change out usage instead.

2022-06-06 15:58 UTC, closed without merging