Add secondary sources
cloudposse/terraform-aws-codebuild pull request #73
Opened 2020-12-29 10:20 UTC by cfir

## what
I am adding dynamic object to support secindary sources 
## why
You are not supporting it right now and we need it.

2021-01-21 10:18 UTC, SweetOps requested changes

2021-01-21 10:18 UTC, SweetOps commented on main.tf
> +      iterator = secondary_source
remove pls `iterator` for consistency with other modules

2021-01-21 10:18 UTC, SweetOps commented on main.tf
> +      for_each = length(var.secondary_sources) > 0 ? var.secondary_sources : []
this condition isn't required

2021-01-21 10:18 UTC, SweetOps commented on main.tf
> +        git_clone_depth = secondary_source.value.git_clone_depth
need to add fallback to `null` for non-required vars (see https://github.com/cloudposse/terraform-aws-codebuild/blob/974c9d579ca18e4a19a11c9ae1dd858ee76de7b9/main.tf#L324 as example)

2021-03-12 19:29 UTC, bcoddens commented
Hey all, what needs to be done to get this integraded ? We need the same feature so if I can help ...

2021-03-16 21:47 UTC, jamengual commented
This feature has been added to the module in #87

2021-03-16 21:47 UTC, closed without merging