Feature/missing arguments
cloudposse/terraform-aws-codebuild pull request #89
Opened 2021-05-19 21:54 UTC by gui-don

## what
* allows user to input a concurrent_build_limit for the codebuild project
* allows user to input a description for the codebuild project

## why
* Missing and needed

2021-05-21 14:50 UTC, SweetOps requested changes

2021-05-21 14:50 UTC, SweetOps commented on variables.tf
> +  default     = ""
```suggestion
  default     = "Managed by Terraform"
```
let's define some value

2021-08-05 13:49 UTC, nitrocode commented
/test all

2021-11-17 07:26 UTC, nitrocode commented on variables.tf
> +  default     = "Managed by Terraform"
```suggestion
  type        = string
  default     = "Managed by Terraform"
```

2021-11-18 00:57 UTC, nitrocode commented
/test all

2021-11-18 00:57 UTC, nitrocode approved these changes

2021-11-18 02:43 UTC, merged